{% set name = "python-gnupg" %}
{% set version = "0.4.6" %}
{% set sha256 = "3aa0884b3bd414652c2385b9df39e7b87272c2eca1b8fcc3089bc9e58652019a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - gnupg

about:
  home: http://pythonhosted.org/python-gnupg
  license: BSD3
  license_file: LICENSE.txt
  summary: A wrapper for the Gnu Privacy Guard (GPG or GnuPG)

extra:
  recipe-maintainers:
    - vamega
