travis:
  secure:
    BINSTAR_TOKEN: BKCkrRfAK2yWdtg1htqI8ThEXO3Hz14HZbGs3pQ/wZx7O590mSyUS3PRFycHcEzeeQXGspI6qDJ2DTc7uKwP7kwEnVm8fdfi432w/BSYtB8FFEYV/CroLVjBwptWxsy66Fx9TvEfjhC743rVwulXoCxlzluxmbBzL85smkL4ts5uS8uyUy1ITMPzHYfrRR/MKZ9vrgUxwCl1mB/j+LgA75XiS5q1IvrDA+Nyq6QTSAlNl13gMpDRuIw2gLIcZvFzISyNEd19DkucQhFSA3B6VI1fyPbS3puLatq8tzrcGnKWinSt7TYT7/2jz5vsZRTqExPbOx5wbFZlV8GYlT8RIYrTT5UBORhgk7fA5B5csJJ0Pwj9EA5D+XrDTbEjlMlIvmOnrzXlUhK3CWqHWms1dWv5vjvrgC0kACk27oZU0HuLNOPOfz9mXu34MiwdqYkqYitMAB9sQa9+tCdVwvXGuBJcNvGlWXprzFHLIZbA5X4DehdCytiAP5hM5FHzreXAD0t6hPZ0o1U7ljhziXzvbxe2LnY0o954vqQTzuEZy+C1lVunyxQrmDiwrg5KQZG+la3sNl5FRZvYDXLRGK35IREZgxq2E+lsg+lLrSMThR6VJEs62aux2v3EDRj1VbkUduNVRK/iUUpW617yidJMhsWZeJ8Wsb1X3XC3e0KQe4g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
