travis:
  secure:
    BINSTAR_TOKEN: GGRSDozDLSZAUM3b3jklgNJco/qfv/lb+yu5gl4kMzmU2uOOZcw9CedZPYxNPDsk6D4OB9Auru8eenC9pfS2r+0bxB4NLNwP4LT3U0MYJngW4UsZmEsyYyZ3S2MrZk9/kseoYYCT1UhW64XI61xCCCGNG4dWpOBK9WVcqXyrdVBELOSp1+rIkropUIB9OkZF7g5VwhuhH+WpA1Gsl7qL/86a4ojmW61QSI/5DG80uktvQGhFLYmiwJyvbjzEOudkcFYDfouzAeQSzu4Rp6TsUrQe2n5Tx1zgE3YNVhlaCQYe53J1LCQB//Wpb+fHynykoheRUvTYJa7Z06LN8Tw0/dBo68IeSFMm22bdvYkSoPeLZ0M91Fk14428JHdLaSdvowmK7EYCWIbZbzcsygIt9lSvsRzJahkKd7yd8o/wsa3ZHxwpqYI1qSuv6GMBdadnnpE8LBEQhkv/5JdpS5RFAjIScycEAXPLr5LRX7/Omnmi4gbrA+/HKWI1V28LlD3fdZZ8WkVE0RBPz0U8mKd6t9VAn41sJITIYFvlf+LIGrEwhgZcJrWBzopSzN1Ew3WZWCbFscLJU8xRHWb/4QLa4mlU02oZKFQnml6bRnXcAD9XYV9FDvhL/W9IwdTS9Dg0HNbw7tycX2C8OnLzgxrbTpmvtDia+Ibej8fNxSHXGyc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
